docs: docs for dwh cost estimates and savings
TobikoData/sqlmesh pull request #3554
Opened 2024-12-21 03:19 UTC by caiters

2024-12-23 21:42 UTC, treysp commented on docs/cloud/features/costs_savings.md
> +- **Prevented Reruns**: If SQLMesh has already run an execution for a change in one environment, we won't need to rerun it in another environment (such as when a model change is backfilled on a devel
It feels the virtual environments bullet is describing this same functionality

2024-12-23 21:42 UTC, treysp reviewed
Thank you! Made a PR against this branch so you can see my edits.

2025-01-07 19:52 UTC, sungchun12 requested changes

2025-01-07 19:52 UTC, sungchun12 commented on docs/cloud/features/costs_savings.md
> +Cloud data warehouses can be expensive, and finance departments are paying attention. When they come asking about your cloud budget, the best preparation is a granular understanding of how your proje
```suggestion
Cloud data warehouses can be expensive, and finance departments are paying attention. When they come asking about your cloud budget, the best preparation is a granular understanding of how your project's data pipelines map to those costs.
```

2025-01-07 19:52 UTC, sungchun12 commented on docs/cloud/features/costs_savings.md
> +This granular cost information allows you to directly explain/justify your cloud warehouse expenditures. It also uncovers the models that could most benefit from efficiency improvements.
```suggestion
This granular cost information allows you to directly explain/justify your cloud warehouse spend. It also uncovers the models that could most benefit from efficiency improvements.
```

2025-01-07 19:52 UTC, sungchun12 commented on docs/cloud/features/costs_savings.md
> +On the General settings page (1), select your pricing plan (2), enter your costs, and then save (3).
What are default pricing plans? Include configs in writing or screenshots for those

2025-01-07 19:52 UTC, sungchun12 commented on docs/cloud/features/costs_savings.md
> +Cost savings are broken up into three main categories:
do we break it down visually or is this math only behind the scenes?

2025-01-07 19:52 UTC, sungchun12 commented on docs/cloud/features/costs_savings.md
> +Cost savings are shown in most of the places data warehouse costs are displayed. You can find how much Tobiko has saved you by viewing the homepage, production environment page, or individual model p
```suggestion
Cost savings are shown in most of the places data warehouse costs are displayed. You can find how much Tobiko Cloud has saved you by viewing the homepage, production environment page, or individual model pages.
```

2025-01-08 01:34 UTC, caiters commented on docs/cloud/features/costs_savings.md
> +Cost savings are broken up into three main categories:
we show them aggregated on the main view, and then if you look at the little info icon you'll get a tooltip with the breakdown!

See image from the cost savings PR here:
![image](https://github.com/user-attachments/assets/84a0addd-fc4e-41ac-9679-2bc4ebef2374)

2025-01-08 01:39 UTC, caiters commented on docs/cloud/features/costs_savings.md
> +On the General settings page (1), select your pricing plan (2), enter your costs, and then save (3).
I think I need a little clarification on this one - are you asking what the default values are for the pricing plans, or just what the form looks like? I could update the `costs-steps.png` file to include the full form with either bigquery or snowflake selected that would show the "cost per TB" or "cost per credit" field as well, or is there something else you are looking for?

2025-01-08 18:38 UTC, sungchun12 commented on docs/cloud/features/costs_savings.md
> +On the General settings page (1), select your pricing plan (2), enter your costs, and then save (3).
"full form with either bigquery or snowflake selected that would show the "cost per TB" or "cost per credit" field as well"

Can you include screenshots of both and explicitly write out the defaults? Ex: BigQuery charges $6.25 per TB processed

<img width="334" alt="image" src="https://github.com/user-attachments/assets/a8b4f7f5-2987-480b-9ef4-27f75eb0b45c" />

2025-01-08 18:39 UTC, sungchun12 commented on docs/cloud/features/costs_savings.md
> +Cost savings are broken up into three main categories:
Replace the costs-example pic with this one you replied in thread. This is much better for the tooltip.

2025-01-09 06:29 UTC, caiters commented on docs/cloud/features/costs_savings.md
> +- **Prevented Reruns**: If SQLMesh has already run an execution for a change in one environment, we won't need to rerun it in another environment (such as when a model change is backfilled on a devel
I think the two are indeed similar so it makes sense that it feels the same, but maybe there's a better way to differentiate? - I can double check with @crericha that this language is correct

2025-01-09 06:47 UTC, caiters commented on docs/cloud/features/costs_savings.md
> +On the General settings page (1), select your pricing plan (2), enter your costs, and then save (3).
Is this along the lines of what you were thinking?

<img width="879" alt="image" src="https://github.com/user-attachments/assets/3a3b3b1b-066b-4777-a2fa-415f6cecc279" />

2025-01-09 17:22 UTC, crericha commented on docs/cloud/features/costs_savings.md
> +On the General settings page (1), select your pricing plan (2), enter your costs, and then save (3).
I worry the code and documentation will get out of sync. It will be hard to remember the docs need to be updated if the defaults change.

2025-01-09 17:36 UTC, sungchun12 commented on docs/cloud/features/costs_savings.md
> +On the General settings page (1), select your pricing plan (2), enter your costs, and then save (3).
Yes, these are the screenshots I was looking for. And @crericha fair point, so @caiters can you add a note along the lines of "These are the current cost defaults at the time of setup and update in Tobiko Cloud as warehouse cost defaults change"

2025-01-09 21:01 UTC, sungchun12 approved these changes

2025-01-09 22:08 UTC, crericha commented on docs/cloud/features/costs_savings.md
> +## Where to find cost and savings estimates information
I suggest introducing savings before where to find them.

2025-01-09 22:12 UTC, crericha commented on docs/cloud/features/costs_savings.md
> +Estimated costs and savings are displayed on the Tobiko Cloud homepage, production environment page, runs and plans pages, and individual model pages.
I believe this is the first time `estimated` is included. Should we add a paragraph to the first section with the disclaimer that it may not 100% match, but is based on the data retrieved from the datawarehouse itself? And then remove estimated from here and elsewhere.

2025-01-09 22:13 UTC, crericha commented on docs/cloud/features/costs_savings.md
> +When calculating your data warehouse costs, Tobiko Cloud also estimates how much money it saved you!
Nit: who is `it` isn't clear here. It could be the dwh or tcloud.

2025-01-09 22:15 UTC, crericha commented on docs/cloud/features/costs_savings.md
> +Cost savings are broken up into three main categories:
`There are three types of cost savings tracked by Tobiko Cloud:`

2025-01-09 22:17 UTC, crericha commented on docs/cloud/features/costs_savings.md
> +- **Prevented Reruns**: If SQLMesh has already run an execution for a change in one environment, we won't need to rerun it in another environment (such as when a model change is backfilled on a devel
`If SQLMesh has already executed the model for the specific interval(s) requested, it knows not to execute the interval(s) again (such as...)`

2025-01-09 22:20 UTC, crericha commented on docs/cloud/features/costs_savings.md
> +- **Unaffected Downstream**: Because SQLMesh understands SQL, we know if a downstream model is not affected by an upstream change and can avoid re-execution.
`we can detect detect when a downstream model is not affected by an upstream change and avoid an re-execution that we know would produce the same data`

2025-01-09 23:42 UTC, crericha commented on docs/cloud/features/costs_savings.md
> +Cost savings are shown in most of the places data warehouse costs are displayed. You can find how much Tobiko Cloud has saved you by viewing the homepage, production environment page, or individual m
Do we not show on the plan page yet?

2025-01-09 23:43 UTC, crericha commented on docs/cloud/features/costs_savings.md
> +- **Prevented Reruns**: If SQLMesh has already run an execution for a change in one environment, we won't need to rerun it in another environment (such as when a model change is backfilled on a devel
I think the rewording you did, after Trey made his comment, addressed the concern and the two classifications sound distinct.

2025-01-13 18:39 UTC, caiters commented on docs/cloud/features/costs_savings.md
> +Estimated costs and savings are displayed on the Tobiko Cloud homepage, production environment page, runs and plans pages, and individual model pages.
we do mention "estimated" beforehand but I will include a disclaimer so it's more clear

2025-01-13 21:11 UTC, caiters commented on docs/cloud/features/costs_savings.md
> +Cost savings are shown in most of the places data warehouse costs are displayed. You can find how much Tobiko Cloud has saved you by viewing the homepage, production environment page, or individual m
Correct - I think we had wanted to be conservative with where we display aggregated costs, so those only live on the listed pages. The Plan page only has costs listed by execution in the model executions table, and we haven't added savings as a column there yet

2025-01-13 22:52 UTC, treysp approved these changes

2025-01-13 22:53 UTC, merged