Chore: Scheduler facade docs
TobikoData/sqlmesh pull request #3558
Opened 2024-12-22 22:39 UTC by erindru

Draft version of the Tobiko Cloud scheduler facade docs

2025-01-05 20:17 UTC, erindru commented
I think [this PR](https://github.com/TobikoData/sqlmesh/pull/3567) needs to be merged first, then i'll rebase on top

2025-01-06 18:45 UTC, sungchun12 commented on docs/cloud/features/scheduler/airflow.md
> +To integrate with Airflow, add the following library to your Airflow runtime environment:
Add an image like this so people know what they should see once this is setup successfully.

![image](https://github.com/user-attachments/assets/b9f88f2d-9fe9-4d64-803b-2d0b20b15ea4)

2025-01-06 18:46 UTC, sungchun12 commented on docs/cloud/features/scheduler/airflow.md
> +You also need to add an Airflow [connection](https://airflow.apache.org/docs/apache-airflow/stable/howto/connection.html#creating-a-connection-with-the-ui) containing your Tobiko Cloud credentials:
add an image of the connection form filled out

2025-01-06 18:49 UTC, sungchun12 commented on docs/cloud/features/scheduler/airflow.md
> +```
```suggestion
```python
```

2025-01-06 18:50 UTC, sungchun12 commented on docs/cloud/features/scheduler/airflow.md
> +```
```suggestion
```python
```

2025-01-06 18:50 UTC, sungchun12 commented on docs/cloud/features/scheduler/airflow.md
> +```
```suggestion
```python
```

2025-01-06 18:50 UTC, sungchun12 commented on docs/cloud/features/scheduler/airflow.md
> +```
```suggestion
```python
```

2025-01-06 18:51 UTC, sungchun12 commented on docs/cloud/features/scheduler/airflow.md
> +```
add an image of the DAG with this slack notification task as a box

2025-01-06 18:57 UTC, sungchun12 requested changes
Overall good, but need more pictures to make it easy to digest at a glance.

2025-01-06 18:57 UTC, sungchun12 commented on docs/cloud/features/scheduler/airflow.md
> +```
add an image of DAG with this update

2025-01-06 18:57 UTC, sungchun12 commented on docs/cloud/features/scheduler/airflow.md
> +```
add an image of DAG with this update

2025-01-06 18:57 UTC, sungchun12 commented on docs/cloud/features/scheduler/airflow.md
> +To integrate with Airflow, add the following library to your Airflow runtime environment:
Move the how it works section here, so people don't have to bounce between 2 tabs.

## How it works
When the platform native DAG runs, it tracks the progress of the equivalent Tobiko Cloud scheduler run. The local tasks reflect the outcome of the remote tasks which allows you to observe at a glance how your data pipeline is progressing, in context with your other pipelines without having to switch to Tobiko Cloud. 

This approach allows us to perform scheduling optimisations that are only possible within our SQLMesh-aware scheduler, while still allowing you to retain the flexibility to attach extra tasks or loop off extra logic within your usual orchestration environment.

Due to the fact that runs are still triggered by the Tobiko Cloud scheduler and the tasks in the local DAG just report on the progress of their remote equivalent in Tobiko Cloud, we call the integration a *facade*.

2025-01-06 18:57 UTC, sungchun12 commented on docs/cloud/features/scheduler/airflow.md
> +Once this DAG is loaded in Airflow, it will be populated with your SQLMesh model structure for the specified `environment` and will be automatically configured to trigger at the same time as the next
add a section on how to debug with this airflow integration by going to the logs tab, clicking the link, and how it shows the debugger view. Include screenshots

2025-01-06 19:01 UTC, sungchun12 commented on docs/cloud/features/scheduler/airflow.md
> +# Airflow
```suggestion
# Airflow

This integration with Tobiko Cloud enables you to synchronize your airflow monitoring and debugging experience with Tobiko Cloud.
```

2025-01-06 20:19 UTC, erindru commented on docs/cloud/features/scheduler/airflow.md
> +To integrate with Airflow, add the following library to your Airflow runtime environment:
The "How it works" section is common to all facades which is why I located it at the top. But I can move it here while Airflow is the only facade

2025-01-06 23:01 UTC, sungchun12 commented on docs/cloud/features/scheduler/airflow.md
> +To integrate with Airflow, add the following library to your Airflow runtime environment:
yep, in the future we may have a more succinct version of the how it works for both airflow and dagster, but in the short term, this makes more sense to the reader in context of what's available in our docs.

2025-01-07 20:26 UTC, sungchun12 commented on docs/cloud/features/scheduler/airflow.md
> +You also need to add an Airflow [connection](https://airflow.apache.org/docs/apache-airflow/stable/howto/connection.html#creating-a-connection-with-the-ui) containing your Tobiko Cloud credentials:
Can you verify this works? I only got it to work without including airflow.

```
(.venv) ➜  tobiko-cloud-demo git:(demo-sung) ✗ pip install tobiko-cloud-scheduler-facade[airflow]
zsh: no matches found: tobiko-cloud-scheduler-facade[airflow]
```

2025-01-07 20:39 UTC, erindru commented on docs/cloud/features/scheduler/airflow.md
> +You also need to add an Airflow [connection](https://airflow.apache.org/docs/apache-airflow/stable/howto/connection.html#creating-a-connection-with-the-ui) containing your Tobiko Cloud credentials:
Here's the pypi link: https://pypi.org/project/tobiko-cloud-scheduler-facade/

```
$ python -m venv venv-test
$ . ./venv-test/bin/activate
(venv-test)  $ python --version
Python 3.10.14
(venv-test) $ pip install tobiko-cloud-scheduler-facade[airflow]
Collecting tobiko-cloud-scheduler-facade[airflow]
  Downloading tobiko_cloud_scheduler_facade-1.0.1-py3-none-any.whl (6.2 kB)
Collecting sqlglot[rs]
  Downloading sqlglot-26.0.1-py3-none-any.whl (437 kB)
...SNIP
Successfully installed
$
```

What version of Python are you using?

Also, @eakmanrq does a wheel for M1 Macs get published?

2025-01-08 00:35 UTC, erindru commented on docs/cloud/features/scheduler/airflow.md
> +You also need to add an Airflow [connection](https://airflow.apache.org/docs/apache-airflow/stable/howto/connection.html#creating-a-connection-with-the-ui) containing your Tobiko Cloud credentials:
I've added a connection form image

2025-01-08 00:40 UTC, erindru commented
@sungchun12 thanks for reviewing, i've addressed your feedback and added a bunch of pictures

2025-01-08 18:52 UTC, sungchun12 commented
> @sungchun12 thanks for reviewing, i've addressed your feedback and added a bunch of pictures

This is great! Going to review Trey's PR that accompanies this too now.

2025-01-08 21:09 UTC, erindru commented on docs/cloud/features/scheduler/airflow.md
> +You also need to add an Airflow [connection](https://airflow.apache.org/docs/apache-airflow/stable/howto/connection.html#creating-a-connection-with-the-ui) containing your Tobiko Cloud credentials:
A thought - is your zsh mangling things due to the square brackets?

Does `pip install 'tobiko-cloud-scheduler-facade[airflow]'` still produce the same error?

2025-01-08 21:11 UTC, erindru commented on docs/cloud/features/scheduler/airflow.md
> +You also need to add an Airflow [connection](https://airflow.apache.org/docs/apache-airflow/stable/howto/connection.html#creating-a-connection-with-the-ui) containing your Tobiko Cloud credentials:
Ah yeah, according to [this](https://stackoverflow.com/questions/30539798/zsh-no-matches-found-requestssecurity) pip's syntax conflicts with zsh's pattern matching syntax so you need to quote the argument if youre using Mac / zsh

2025-01-08 21:36 UTC, sungchun12 commented on docs/cloud/features/scheduler/airflow.md
> +You also need to add an Airflow [connection](https://airflow.apache.org/docs/apache-airflow/stable/howto/connection.html#creating-a-connection-with-the-ui) containing your Tobiko Cloud credentials:
That works, thank you! I'll go ahead and approve.

2025-01-08 21:36 UTC, sungchun12 approved these changes

2025-01-08 21:39 UTC, merged