Chore: Document the cloud scheduler feature
TobikoData/sqlmesh pull request #3567
Opened 2024-12-26 19:47 UTC by izeigerman

Self-hosed executors are not documented as part of this change. Relevant sections will be added in later iterations.

2024-12-26 19:47 UTC, izeigerman commented on docs/cloud/features/scheduler.md
> +Tobiko Cloud offers scheduling capabilities that have several advantages over the scheduler built into the open source version of SQLMesh.
@tobymao can you check whether this is missing any additional advantages.

2025-01-06 18:08 UTC, tobymao commented on docs/cloud/features/scheduler.md
> +Tobiko Cloud offers scheduling capabilities that have several advantages over the scheduler built into the open source version of SQLMesh.
looks great

2025-01-06 18:28 UTC, sungchun12 commented on docs/cloud/features/scheduler.md
> +default_gateway: my_cloud_gateway
```suggestion
gateways:
  my_cloud_gateway:
    scheduler:
      type: cloud
    connection: # This connection is used for automatic unit test generation
        type: postgres
        user: postgres
        password: postgres
        host: localhost
        port: 5432
        database: postgres

default_gateway: my_cloud_gateway
```

2025-01-06 18:33 UTC, sungchun12 commented on docs/cloud/features/scheduler.md
> +TBD
```suggestion
Coming soon!
```

2025-01-06 18:35 UTC, sungchun12 requested changes
made quick suggestions, once those are committed, I'll approve. Overall great job

2025-01-06 21:40 UTC, izeigerman commented on docs/cloud/features/scheduler.md
> +default_gateway: my_cloud_gateway
`connection` is not required for this to work. Why would we need this?

2025-01-06 21:49 UTC, izeigerman commented
@sungchun12 addressed all comments except one. Please see the thread

2025-01-06 23:02 UTC, sungchun12 commented on docs/cloud/features/scheduler.md
> +default_gateway: my_cloud_gateway
If we want to enable automatic unit test creation. We debugged this here: https://tobikodata.slack.com/archives/C065Y4BNYJJ/p1734647889738389?thread_ts=1734645873.670879&cid=C065Y4BNYJJ

2025-01-06 23:45 UTC, tobymao approved these changes

2025-01-07 01:26 UTC, sungchun12 commented on docs/cloud/features/scheduler.md
> +default_gateway: my_cloud_gateway
I want to make sure people can still generate unit test configs after they add the tcloud scheduler.

2025-01-07 01:40 UTC, tobymao commented on docs/cloud/features/scheduler.md
> +default_gateway: my_cloud_gateway
most people won’t need that though.

2025-01-07 16:45 UTC, izeigerman commented on docs/cloud/features/scheduler.md
> +default_gateway: my_cloud_gateway
yeah, + one of the benefits (`Access Control`) assumes that you don't need the connection config for individual clients. Including this block will make it confusing

2025-01-07 19:54 UTC, sungchun12 commented on docs/cloud/features/scheduler.md
> +default_gateway: my_cloud_gateway
got it, you can ignore this suggestion then. I'll approve

2025-01-07 19:54 UTC, sungchun12 approved these changes

2025-01-07 20:09 UTC, treysp approved these changes

2025-01-07 20:41 UTC, merged